POST http://localhost:3000/admin/add-book HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0MDgiLCJpYXQiOjE2MTk1Mjk5NjEsImV4cCI6MTYxOTUzMzU2MX0.U75dAvolYPwULuQepd9q5QkC0XDC4YR2YDVXoW1sLwM

{    
    "name": "Classic Data Structures",
    "isbn": "9788120337312",
    "totalCopies": "2",
    "author": "Samanta Debasis",
    "publisher": "PHI Learning Pvt. Ltd., 2009",
    "tags": ["DS", "GATE", "CODING"]
}
###
POST http://localhost:3000/admin/add-book HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0MDgiLCJpYXQiOjE2MTk1Mjk5NjEsImV4cCI6MTYxOTUzMzU2MX0.U75dAvolYPwULuQepd9q5QkC0XDC4YR2YDVXoW1sLwM

{    
    "name": "Data Structures And Algorithmic Thinking With Python",
    "isbn": "9788192107592",
    "totalCopies": "1",
    "author": "Narasimha Karumanchi",
    "publisher": "CareerMonk.com",
    "tags": ["DS", "GATE", "CODING", "PYTHON"]
}
###
POST http://localhost:3000/admin/add-book HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0MDgiLCJpYXQiOjE2MTk1MzU5MDUsImV4cCI6MTYxOTUzOTUwNX0.MXyBZ73mfxSpvozS2A7yTe12ORjgn2nwg0S6KVOrTtM

{    
    "name": "Data Structures And Algorithms Made Easy",
    "isbn": "9788193245279",
    "totalCopies": "1",
    "author": "Narasimha Karumanchi",
    "publisher": "CareerMonk.com",
    "tags": ["DS", "GATE", "CODING"]
}
###
POST http://localhost:3000/admin/add-book HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0MDgiLCJpYXQiOjE2MTk1Mjk5NjEsImV4cCI6MTYxOTUzMzU2MX0.U75dAvolYPwULuQepd9q5QkC0XDC4YR2YDVXoW1sLwM

{    
    "name": "Introduction to Algorithms",
    "isbn": "9780262033848",
    "totalCopies": "3",
    "author": "Thomas H. Cormen",
    "publisher": "The MIT Press",
    "tags": ["DAA", "GATE", "CODING"]
}
###
POST http://localhost:3000/admin/add-book HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0MDgiLCJpYXQiOjE2MTk1Mjk5NjEsImV4cCI6MTYxOTUzMzU2MX0.U75dAvolYPwULuQepd9q5QkC0XDC4YR2YDVXoW1sLwM

{    
    "name": "Discrete And Combinatorial Mathematics",
    "isbn": "9780072525663",
    "totalCopies": "5",
    "author": "Richard M. Grassl",
    "publisher": "McGraw-Hill Primis",
    "tags": ["DM", "GATE"]
}
###
POST http://localhost:3000/admin/add-book HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0MDgiLCJpYXQiOjE2MTk1Mjk5NjEsImV4cCI6MTYxOTUzMzU2MX0.U75dAvolYPwULuQepd9q5QkC0XDC4YR2YDVXoW1sLwM

{    
    "name": "Computer Organization and Architecture: Designing for Performance",
    "isbn": "9780133599855",
    "totalCopies": "5",
    "author": "Stallings, William",
    "publisher": "Prentice Hall",
    "tags": ["COA", "GATE"]
}
###
POST http://localhost:3000/admin/add-book HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0MDgiLCJpYXQiOjE2MTk1Mjk5NjEsImV4cCI6MTYxOTUzMzU2MX0.U75dAvolYPwULuQepd9q5QkC0XDC4YR2YDVXoW1sLwM

{    
    "name": "Computer system architecture",
    "isbn": "9780133599855",
    "totalCopies": "5",
    "author": "Mano, M. Morris",
    "publisher": "Prentice Hall",
    "tags": ["COA", "GATE"]
}
###