POST http://localhost:3000/student/register HTTP/1.1
Content-Type: application/json

{    
    "studentId": "B161480",
    "name": "Ramanakishore",
    "joinYear": "2016",
    "sem": "E3S2",
    "class": "AB-2, 309",
    "mobile": "9177887457",
    "email": "ramana@gmail.com",
    "address": "basar",
    "password": "Rama@B16"
}
###
POST http://localhost:3000/student/login HTTP/1.1
Content-Type: application/json

{    
    "studentId": "B161480",
    "password": "Rama@B16"
}
###
POST http://localhost:3000/student/logout HTTP/1.1
Content-Type: application/json

{    
    "studentId": "B161480"
}
###
GET http://localhost:3000/student/get-profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0MDgiLCJpYXQiOjE2MTkzNjMyNzYsImV4cCI6MTYxOTM2Njg3Nn0.1PVaNUJFZeC2UKJkRWmAdyqAh1lniwN8sLcEhec9g9U
###
PATCH  http://localhost:3000/student/update-profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0MDgiLCJpYXQiOjE2MTkzNjc2MTksImV4cCI6MTYxOTM3MTIxOX0.vdfk318eA-zYJ5f4xiqqGQ0f_8WD7YPWMfsXlBdycDg

{    
    "studentId": "B161480",
    "name": "Ramanakishore Peroji",
    "joinYear": "2016",
    "sem": "E3S2",
    "class": "AB-2, 309",
    "mobile": "9177887457",
    "email": "ramana@gmail.com",
    "address": "basar"
}
###
DELETE http://localhost:3000/student/delete-account HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0MDgiLCJpYXQiOjE2MTkzNjMyNzYsImV4cCI6MTYxOTM2Njg3Nn0.1PVaNUJFZeC2UKJkRWmAdyqAh1lniwN8sLcEhec9g9U
###
POST http://localhost:3000/student/forgot-password HTTP/1.1
Content-Type: application/json

{    
    "studentId": "B161480"
}
###
POST http://localhost:3000/student/reset-password HTTP/1.1
Content-Type: application/json

{    
    "studentId": "B161480",
    "password": "Rgukt@213",
    "repeatPassword": "Rgukt213"
}
###
POST http://localhost:3000/student/send-otp HTTP/1.1
Content-Type: application/json

{    
    "mobile": "9177887457"
}
###
POST http://localhost:3000/student/verify-otp HTTP/1.1
Content-Type: application/json

{    
    "otp": "95094",
    "requestId": "jt8nwzioehyf7md"
}
###
GET http://localhost:3000/student/get-book HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0ODAiLCJpYXQiOjE2MTk1Mzk4MDQsImV4cCI6MTYxOTU0MzQwNH0.HqshFH-13ijdbRQREzC7sVgmqpMMa1WncQUx_6jUN18

{    
    "isbn": "9788193245279"
}
###
GET http://localhost:3000/student/get-books-by-name HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0MDgiLCJpYXQiOjE2MTkzNjMyNzYsImV4cCI6MTYxOTM2Njg3Nn0.1PVaNUJFZeC2UKJkRWmAdyqAh1lniwN8sLcEhec9g9U

{    
    "name": "Algo"
}
###
GET http://localhost:3000/student/get-books-by-tags HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0MDgiLCJpYXQiOjE2MTkzNjMyNzYsImV4cCI6MTYxOTM2Njg3Nn0.1PVaNUJFZeC2UKJkRWmAdyqAh1lniwN8sLcEhec9g9U

{    
    "tags": ["GATE", "APTITUDE","CODING"]
}
###
POST http://localhost:3000/student/order-book HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0ODAiLCJpYXQiOjE2MTk1MzU5NjEsImV4cCI6MTYxOTUzOTU2MX0.iCbV0JkDQOSfGUQlqy53gBB1ncF4D-uDgs0g0rGnmhU

{    
    "isbn": "9788193245279",
    "days": "30"
}
###
POST http://localhost:3000/student/extend-order HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0ODAiLCJpYXQiOjE2MTk1MzU5NjEsImV4cCI6MTYxOTUzOTU2MX0.iCbV0JkDQOSfGUQlqy53gBB1ncF4D-uDgs0g0rGnmhU

{    
    "isbn": "9788193245279",
    "days": "5",
    "reason": "GATE Preparation"
}
###
GET http://localhost:3000/student/get-recommended-books HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkIxNjE0ODAiLCJpYXQiOjE2MTk1NDM1MzIsImV4cCI6MTYxOTU0NzEzMn0.2kZK2qcU7VI7LdBnil_e4bo_hksTRNARVmvLgw2jjqQ
###